### ISSUE TITLE
Unable to SSH into Login Node Deployed with hpc-toolkit due to IAM Permissions Issue

### ISSUE THREAD

**Issue by gouki510** [GoogleCloudPlatform/cluster-toolkit#2950]
#### **Issue Description:**

I am unable to SSH into the login node that was deployed using the `hpc-toolkit`. The error message encountered is as follows:

```
Insufficient IAM permissions. The instance belongs to an external organization. 
You must be granted the roles/compute.osLoginExternalUser IAM role on the external organization to configure POSIX account information.
```

#### **Details:**

- The `enable-oslogin` flag on the login node is set to `TRUE`.
- The following IAM roles are assigned to the user:

  - Compute OS Login
  - Compute OS Admin Login
  - Compute Instance Admin (v1)
  - IAP-secured Tunnel User
  - Pub/Sub Admin
  - Storage Object Admin
  - Owner
  - Service Account User
  - Editor

- The project is classified as "no organization," which prevents the assignment of the `roles/compute.osLoginExternalUser` role.

Given the constraints of a "no organization" project, how can I successfully SSH into the login node? Is there an alternative approach or workaround that can be used in this scenario?

**Comment by gouki510** [comment]
resolved

**Comment by nick-stroud** [comment]
@gouki510, I see you closed this issue several days after opening it. Did you find a solution to your issue. If so would you mind sharing it here?
