### ISSUE TITLE
Logging to BigQuery can fail if number of rows to insert is too large

### ISSUE THREAD

**Issue by fdmalone** [GoogleCloudPlatform/cluster-toolkit#3008]
Pulled from #2989. I ran into an issue where load_bq.py would fail as the number of rows was too large for [insert_rows](https://github.com/GoogleCloudPlatform/cluster-toolkit/blob/1e38ce0c2353a3b14520043ab27514d8defd2d71/community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/load_bq.py#L270). My workaround was to batch over slices of the `jobs` list with a batch size set to 10000 (which I think is the upper limit for insert_rows).

I can send a PR with the patch but I was a bit hesitant given the lack of unit tests for the script and adding those would be a bit of work (faking the client etc)

**Comment by mr0re1** [comment]
@fdmalone , your contribution would be very welcome, with or without tests.

**Comment by cdunbar13** [comment]
Checking in to see if you've had a chance to submit a PR for this.

**Comment by fdmalone** [comment]
I haven't, I'll try to get to it shortly

**Comment by tpdownes** [comment]
Marking this issue as "fixed, not released" because it is on our develop branch. It should be in the next release, which will probably be numbered v1.41.0.

**Comment by cdunbar13** [comment]
It looks like this has been released into 1.41.0.  I will close this, please re-open if there is an issue.
