### ISSUE TITLE
Deploying latest nvidia driver cuda 12.4 breaks TCPX on A3 high from functioning correctly

### ISSUE THREAD

**Issue by saltysoup** [GoogleCloudPlatform/cluster-toolkit#3032]
https://github.com/GoogleCloudPlatform/cluster-toolkit/blob/7699f5d1002b58974183370931ba76454b88526f/examples/machine-learning/a3-highgpu-8g/ml-slurm-a3-1-image.yaml#L87

A customer reported that the latest nvidia driver being installed prevents TCPX from working correctly as jobs die with error message with multiple NCCL timeout errors during NCCL group initialisation. 

Can you please confirm this behaviour? I dont think Slurm v5/v6 matters here, as both of these modules pull the latest nvidia driver without version pinning, and i suspect the new version is breaking compatibility with the NCCL Plugin and RxDM container 

`NCCL INFO Call to connect returned Connection refused, retrying`

**Comment by cdunbar13** [comment]
Hi, I will look into this.  Do you have any additional information, including any modifications that your customer may have made to the example blueprint?

**Comment by tpdownes** [comment]
Closing this issue as deploying CUDA/driver versions beyond the versions in the base image for A3 High is not supported.
