### ISSUE TITLE
GKE default nodepool's upgrade settings are not configurable

### ISSUE THREAD

**Issue by chajath** [GoogleCloudPlatform/cluster-toolkit#3441]
Following up to https://github.com/GoogleCloudPlatform/cluster-toolkit/issues/3343, it'd be great if the upgrade settings can be applied on modules/scheduler/gke-cluster, too, to specify default cluster's upgrade settings. As of now, they are hardcoded:

https://github.com/GoogleCloudPlatform/cluster-toolkit/blob/0a8385bd79cad3881732404b05c5fd3c433e4386/modules/scheduler/gke-cluster/main.tf#L243-L246

**Comment by ighosh98** [comment]
Don't see any other instances of upgrade_settings. Have made a PR to address this request. @chajath will free to take a look at the PR or please let us know if there are other occurences of the same issue that you came across.
