### ISSUE TITLE
General comment

### ISSUE THREAD

**Issue by ziwang492** [GoogleCloudPlatform/cluster-toolkit#56]
I realized a few things while running slurm jobs from the toolkit 

setting up the compute partitions with n2 instances
- "Unsupported placement policy configuration. Please utilize c2 machine type."

Also, each time I need to run make before running ./ghpc create --config <path to config> or it will take the older config version, not sure where in the code its doing that, it seem likes its doing some temp folder each time ghpc make runs.

**Comment by mr0re1** [comment]
*__Please ignore.__* *It's a touch to trigger sync*
